version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nj-api
    restart: unless-stopped
    environment:
      - GCP_PROJECT_ID=123456
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/nj-db.json
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - ~/.gcloud/nj-db.json:/usr/nj-db.json
